import numbers
import re
import sqlite3
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SQL_PATH = ROOT / "sql" / "analysis_queries.sql"
DB_PATH = ROOT / "data" / "warehouse.db"
RESULTS_PATH = ROOT / "sql" / "query_results.md"


def parse_queries(text):
    queries = []
    for chunk in text.split(";"):
        title_match = re.search(r"^\s*--\s*query:\s*(.+)$", chunk, re.MULTILINE)
        if not title_match:
            continue
        body = "\n".join(
            line for line in chunk.splitlines() if not line.strip().startswith("--")
        ).strip()
        if body:
            queries.append((title_match.group(1).strip(), body))
    return queries


def format_value(value):
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "-"
    if isinstance(value, numbers.Integral):
        return f"{value:,}"
    if isinstance(value, numbers.Real):
        return f"{float(value):,.6f}".rstrip("0").rstrip(".")
    return str(value).replace("|", "\\|")


def render_table(frame):
    if frame.empty:
        return "_No rows returned._"
    columns = [str(column) for column in frame.columns]
    numeric = [
        pd.api.types.is_numeric_dtype(frame[column]) for column in frame.columns
    ]
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---:" if flag else "---" for flag in numeric) + " |"
    rows = [
        "| " + " | ".join(format_value(value) for value in row) + " |"
        for row in frame.itertuples(index=False, name=None)
    ]
    return "\n".join([header, separator] + rows)


def main():
    queries = parse_queries(SQL_PATH.read_text(encoding="utf-8"))
    connection = sqlite3.connect(DB_PATH)

    sections = [
        "# SQL Query Results",
        "",
        "Generated by `src/run_queries.py` from `sql/analysis_queries.sql`.",
        "",
        f"Queries executed: **{len(queries)}**",
        "",
    ]

    for position, (title, sql) in enumerate(queries, start=1):
        frame = pd.read_sql_query(sql, connection)
        sections += [
            f"## {position}. {title}",
            "",
            "```sql",
            sql,
            "```",
            "",
            render_table(frame),
            "",
            f"_{len(frame)} row(s) returned._",
            "",
        ]
        print(f"{position:>2}. {title:<45} {len(frame)} rows")

    connection.close()
    RESULTS_PATH.write_text("\n".join(sections), encoding="utf-8")
    print(f"wrote {RESULTS_PATH}")


if __name__ == "__main__":
    main()
